// demo-react/src/App.tsx
import React, { useState, useEffect } from 'react'
import Phaser from 'phaser'
import { IonPhaser, GameInstance } from '@ion-phaser/react'
import logo from './assets/logo.png'

import './App.css'

class MainScene extends Phaser.Scene {
  private helloWorld!: Phaser.GameObjects.Text

  init () {
    this.cameras.main.setBackgroundColor('#24252A')
  }

  create () {
    this.helloWorld = this.add.text(
      this.cameras.main.centerX, 
      this.cameras.main.centerY, 
      "Hello World", { 
        font: "40px Arial", 
        fill: "#ffffff" 
      }
    );
    this.helloWorld.setOrigin(0.5);
  }
  update () {
    this.helloWorld.angle += 1;
  }
}

const gameConfig: GameInstance = {
  width: "100%",
  height: "100%",
  type: Phaser.AUTO,
  scale: {
    mode: Phaser.Scale.FIT,
    autoCenter: Phaser.Scale.CENTER_BOTH,
    width: '100%',
    height: '100%'
  },
  render: {
    antialias: false,
    pixelArt: true,
    roundPixels: true
  },
  physics: {
    default: 'arcade',
    arcade: {
      gravity: { y: 400 },
      debug: true
    }
  },
  scene: MainScene
};

export default function App () {
  const [game, setGame] = useState<GameInstance>()
  const [initialize, setInitialize] = useState(false)

  const destroy = () => {
    console.log('Instance', game?.instance)
    setInitialize(false)
    setGame(undefined)
  }

  useEffect(() => {
    if (initialize) {
      setGame(Object.assign({}, gameConfig))
    }
  }, [initialize])

  return (
    <div className="App">
      <header className="App-header">
        { initialize ? (
          <>
            <IonPhaser game={game} initialize={initialize} />
            <div onClick={destroy} className="flex destroyButton">
              <a href="#1" className="bttn">Destroy</a>
            </div>
          </>
        ) : (
          <>
            <img src={logo} className="App-logo" alt="logo" />
            <div onClick={() => setInitialize(true)} className="flex">
              <a href="#1" className="bttn">Initialize</a>
            </div>
          </>
        )}
      </header>
    </div>
  );
}

// demo-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import * as Phaser from 'phaser';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  initialize = false;
  game = {
    width: "100%",
    height: "100%",
    type: Phaser.AUTO,
    scene: {
      init: function() {
        this.cameras.main.setBackgroundColor('#24252A')
      },
      create: function() {
        this.helloWorld = this.add.text(
          this.cameras.main.centerX, 
          this.cameras.main.centerY, 
          "Hello World", { 
            font: "40px Arial", 
            fill: "#ffffff" 
          }
        );
        this.helloWorld.setOrigin(0.5);
      },
      update: function() {
        this.helloWorld.angle += 1;
      }
    },
    instance: null
  }

  initializeGame() {
    this.initialize = true

    setTimeout(() => {
      console.log(this.game.instance)
    }, 3000)
  }
}

<div class="App">
  <header class="App-header">
    <ng-container *ngIf="!initialize">
      <img src="../assets/logo.png" class="App-logo" alt="logo" />
      <div (click)="initializeGame()" class="flex">
        <a href="#1" class="bttn">Initialize</a>
      </div>
    </ng-container>
    <ion-phaser [game]="game" [initialize]="initialize"></ion-phaser>
  </header>
</div>
